export const mainPortfolioData = [
  {
    id: 1,
    cover: "/images/quoteGenerator/cover.webp",
    image: "/images/quoteGenerator/cover.webp",
    title: "Quote Generator App",
    chips: ["React", "API", "Axios"],
    desc: "Генератор аниме цитат из открытого API с функцией sharing в Твиттер.",
    livePreview: "https://berdibekovadilet.github.io/quote_generator/",
    github: "https://github.com/berdibekovadilet/quote_generator",
  },
  {
    id: 2,
    cover: "/images/crabsburgers/cover.webp",
    image: "/images/crabsburgers/page.webp",
    title: "Crabsburgers",
    chips: ["Next", "Mockapi", "Routing"],
    desc: "Простое приложение на Next JS про крабсбурегеры из мультика Спанч-Боба.",
    livePreview: "https://burger-nextjs.vercel.app/",
    github: "https://github.com/berdibekovadilet/burger_nextjs",
  },
  {
    id: 3,
    cover: "/images/helpdesk/cover.webp",
    image: "/images/helpdesk/page.webp",
    title: "Helpdesk",
    chips: ["Next", "Module.scss", "Framer Motion"],
    desc: "Действуйщий сайт занимающийся арендой серверов и системным администрированием.",
    livePreview: "https://helpdesk.kg/",
    github: "https://github.com/berdibekovadilet/server_rent_nextjs",
  },
  {
    id: 4,
    cover: "/images/urlshorting/1.webp",
    image: "/images/urlshorting/1.webp",
    title: "URL Shorting",
    chips: ["React", "Redux", "API"],
    desc: "Простое приложение которое сокращает ссылки, сделанна на React с применением Redux Toolkit и API.",
    livePreview: "https://urlshorting.netlify.app/",
    github: "https://github.com/berdibekovadilet/url-shorting-app",
  },
  {
    id: 5,
    cover: "/images/casio/cover.webp",
    image: "/images/casio/page.webp",
    title: "Casio Ecommerce",
    chips: ["React", "Redux", "Mockapi"],
    desc: "Интернет-магазин часов Casio с функциями поиска, фильтра, пагинаций и корзины сделанная на Redux Toolkit.",
    livePreview: "https://casiowatch.netlify.app/",
    github: "https://github.com/berdibekovadilet/watch_ecommerce",
  },
  {
    id: 6,
    cover: "/images/courses/cover.webp",
    image: "/images/courses/cover.webp",
    title: "Courses (В разработке)",
    chips: ["Next", "Typescript", "Redux"],
    desc: "Приложением про курсы ИТ на Next JS и Typescript приближенный к профессиональному продакшену.",
    livePreview: "https://courses-choose.vercel.app/",
    github: "https://github.com/berdibekovadilet/top_app",
  },
];

export const addPortfolioData = [
  {
    id: 1,
    title: "Todo React",
    livePreview: "https://todoadilet.netlify.app/",
    github: "https://github.com/berdibekovadilet/todo_react",
  },
  {
    id: 2,
    title: "Todo Typescript",
    livePreview: "https://todo-typescript-omega.vercel.app/",
    github: "https://github.com/berdibekovadilet/todo_typescript",
  },
  {
    id: 3,
    title: "Tailwind Landing",
    livePreview: "https://insurance-website.vercel.app/",
    github: "https://github.com/berdibekovadilet/insurance_website",
  },
  {
    id: 4,
    title: "MUI Social",
    livePreview: "https://mui-project-one.vercel.app/",
    github: "https://github.com/berdibekovadilet/mui_project",
  },
  {
    id: 5,
    title: "Admin Dashboard",
    livePreview: "https://admindashboard12.netlify.app/",
    github: "https://github.com/berdibekovadilet/admindahboard",
  },
  {
    id: 6,
    title: "Portfolio site",
    livePreview: "https://adilet-com.vercel.app/",
    github: "https://github.com/berdibekovadilet/adilet_com",
  },
];

export const socialData = [
  {
    id: 1,
    text: "+7(930)930-6674",
    icon: "/icons/iconWhatsapp.svg",
    link: "https://wa.me/+79309306674",
  },
  {
    id: 2,
    text: "@adiletberdibekov",
    icon: "/icons/iconTelegram.svg",
    link: "https://t.me/adiletberdibekov",
  },
  {
    id: 3,
    text: "berdibekovadilet@gmail.com",
    icon: "/icons/iconMail.svg",
    link: "mailto:berdibekovadilet@gmail.com",
  },
];
