export const mainPortfolioData = [
  {
    id: 1,
    cover: "/images/casiostore/1.webp",
    image: "/images/casiostore/1.webp",
    title: "Casio Store",
    chips: ["React", "Redux", "Typescript"],
    desc: "Интернет-магазин React. Реюзабельные компоненты, удобная структура папок, функционал фильтрации и сортировки.",
    livePreview: "https://casio-store.vercel.app/",
    github: "https://github.com/berdibekovadilet/casio-store",
  },
  {
    id: 2,
    cover: "/images/appart/1.webp",
    image: "/images/appart/1.webp",
    title: "Appart - Real Estate App",
    chips: ["Next", "Framer Motion", "Yandex Maps"],
    desc: "Appart приложение на рынке недвижимости, с разделами под покупку и аренду квартир, домов, коттеджей.",
    livePreview: "https://appart-one.vercel.app/",
    github: "https://github.com/berdibekovadilet/appart-client",
  },
  {
    id: 3,
    cover: "/images/urlshorting/1.webp",
    image: "/images/urlshorting/1.webp",
    title: "URL Shorting",
    chips: ["React", "Redux", "API"],
    desc: "Простое приложение которое сокращает ссылки, сделанна на React с применением Redux Toolkit и API.",
    livePreview: "https://urlshorting.netlify.app/",
    github: "https://github.com/berdibekovadilet/url-shorting-app",
  },
  {
    id: 4,
    cover: "/images/crabsburgers/cover.webp",
    image: "/images/crabsburgers/page.webp",
    title: "Crabsburgers",
    chips: ["Next", "Mockapi", "Routing"],
    desc: "Простое приложение на Next JS про крабсбурегеры из мультика Спанч-Боба.",
    livePreview: "https://burger-nextjs.vercel.app/",
    github: "https://github.com/berdibekovadilet/burger_nextjs",
  },
  {
    id: 5,
    cover: "/images/realtor/1.webp",
    image: "/images/realtor/1.webp",
    title: "Realtor",
    chips: ["Next", "Axios", "Chakra UI"],
    desc: "Приложением по поиску недвижимости на Next JS с использованием стороннего API. Компоненты на Chakra UI.",
    livePreview: "https://realtor-sable.vercel.app/",
    github: "https://github.com/berdibekovadilet/realtor",
  },
  {
    id: 6,
    cover: "/images/musicblog/1.webp",
    image: "/images/musicblog/1.webp",
    title: "Music blog",
    chips: ["React", "Express", "Mongoose"],
    desc: "Fullstack блог с использованием React и Express.js. Есть функции создание, редактирования и удаления поста.",
    livePreview: "https://mern-music-blog.netlify.app/",
    github: "https://github.com/berdibekovadilet/music-blog-client",
  },
  {
    id: 7,
    cover: "/images/helpdesk/cover.webp",
    image: "/images/helpdesk/page.webp",
    title: "Helpdesk",
    chips: ["Next", "Module.scss", "Framer Motion"],
    desc: "Действуйщий сайт занимающийся арендой серверов и системным администрированием.",
    livePreview: "https://helpdesk.kg/",
    github: "https://github.com/berdibekovadilet/server_rent_nextjs",
  },

  {
    id: 8,
    cover: "/images/casio/cover.webp",
    image: "/images/casio/page.webp",
    title: "Watch Store",
    chips: ["React", "Redux", "Mockapi"],
    desc: "Интернет-магазин часов с функциями поиска, фильтра, пагинаций и корзины сделанная на Redux Toolkit.",
    livePreview: "https://casiowatch.netlify.app/",
    github: "https://github.com/berdibekovadilet/watch_ecommerce",
  },
  {
    id: 9,
    cover: "/images/courses/cover.webp",
    image: "/images/courses/cover.webp",
    title: "Courses Finder",
    chips: ["Next", "Typescript", "Redux"],
    desc: "Приложением про курсы ИТ на Next JS и Typescript приближенный к профессиональному продакшену.",
    livePreview: "https://courses-choose.vercel.app/",
    github: "https://github.com/berdibekovadilet/top_app",
  },
];

export const miniPortfolioData = [
  {
    id: 1,
    title: "Quote Generator",
    livePreview: "https://berdibekovadilet.github.io/quote_generator/",
    github: "https://github.com/berdibekovadilet/quote_generator",
  },
  {
    id: 2,
    title: "Tailwind Landing",
    livePreview: "https://insurance-website.vercel.app/",
    github: "https://github.com/berdibekovadilet/insurance_website",
  },
  {
    id: 3,
    title: "MUI Social",
    livePreview: "https://mui-project-one.vercel.app/",
    github: "https://github.com/berdibekovadilet/mui_project",
  },
  {
    id: 4,
    title: "Admin Dashboard",
    livePreview: "https://admindashboard12.netlify.app/",
    github: "https://github.com/berdibekovadilet/admindahboard",
  },
  {
    id: 5,
    title: "Redux Thunk",
    livePreview: "https://rtklasyncthunk.netlify.app/",
    github: "https://github.com/berdibekovadilet/reduxt-toolkit",
  },
  {
    id: 6,
    title: "Swiper React TS",
    livePreview: "https://swiper-react.netlify.app/",
    github: "https://github.com/berdibekovadilet/swiper-react",
  },
];

export const backPortfolioData = [
  {
    id: 1,
    title: "Casio Store Server",
    chips: ["Nest", "Postgres", "Swagger"],
    github: "https://github.com/berdibekovadilet/casio-server",
  },
  {
    id: 2,
    title: "Music App Server",
    chips: ["Nest", "Mongoose", "Typescript"],
    github: "https://github.com/berdibekovadilet/music-app-server",
  },
  {
    id: 3,
    title: "Online Store Pern",
    chips: ["Express", "Postgres", "Sequelize"],
    github: "https://github.com/berdibekovadilet/online-store-pern",
  },
  {
    id: 4,
    title: "Musci Blog Mern",
    chips: ["Express", "Mongoose", "Jsonwebtoken"],
    github: "https://github.com/berdibekovadilet/mern-music-blog",
  },
];

export const socialData = [
  {
    id: 1,
    text: "+7(930)930-6674",
    icon: "/icons/iconWhatsapp.svg",
    link: "https://wa.me/+79309306674",
  },
  {
    id: 2,
    text: "@adiletberdibekov",
    icon: "/icons/iconTelegram.svg",
    link: "https://t.me/adiletberdibekov",
  },
  {
    id: 3,
    text: "berdibekovadilet@gmail.com",
    icon: "/icons/iconMail.svg",
    link: "mailto:berdibekovadilet@gmail.com",
  },
];
